[supervisord]
nodaemon=true
user=root
loglevel=warn
environment=INSTANCE_NAME=captaincredz
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:timer]
priority=10
command=python /app/timer/timer.py
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:storage]
priority=10
command=python /app/storage/storage.py
autostart=true
autorestart=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sprayer]
priority=99
command=sh -c 'python /app/sprayer/sprayer.py; kill -15 $(cat /var/run/supervisord.pid)'
stopasgroup=true
killasgroup=true
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:plugin]
priority=10
command=python /app/plugin/plugin.py
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0